// Every label the mod draws, in English, in one table so it can be translated
// later. Catalogue entries (strategy options, tutor models, themes) keep their
// labels next to their ids; prompts sent to the model are not labels.
export const LABELS = {
    modName: 'lingo-pane',
    // --- Setup ------------------------------------------------------------------
    setupTitle: 'lingo-pane setup',
    setupStep: (n, of) => `Step ${n} of ${of}`,
    setupHintTyping: 'Type, Enter keeps the text, Tab moves to the next field or button.',
    setupHintLevel: 'Tab moves between buttons and Enter presses, or type the digit shown.',
    setupHintButtons: 'Tab moves between buttons and Enter presses.',
    setupLanguagesAsk: 'Which languages? The explanations are in your native language.',
    setupNative: 'Native language: ',
    setupTarget: 'Target language: ',
    setupNativePlaceholder: 'e.g. Spanish',
    setupTargetPlaceholder: 'e.g. English',
    setupLevelAsk: (target) => `Your level in ${target} (CEFR):`,
    setupLevelNone: 'None picked yet.',
    setupLevelPicked: (level) => `Picked: ${level}`,
    setupInterestsAsk: 'What do you like to talk about? Role-play scenarios are made from it.',
    setupInterestsNote: 'Optional, comma-separated, up to 5.',
    setupInterests: 'Interests: ',
    setupInterestsPlaceholder: 'e.g. chess, cooking, startups',
    setupPlacementTitle: 'Placement test (optional)',
    setupPlacementLater: 'placement test: coming later',
    setupStrategiesAsk: 'How should it work? Defaults are fine; "coming later" ones are not built yet.',
    setupComingLater: (label) => `${label} (coming later)`,
    setupPreferencesAsk: 'How the lesson looks and who teaches. Defaults are fine.',
    setupShareTitle: 'Split width while Claude works (share of the terminal)',
    setupShare: (share) => `${share} %`,
    setupTutorTitle: 'Tutor model',
    setupTutorNote: 'Every tutor reply uses your Claude plan.',
    setupThemeTitle: 'Theme',
    setupContextTitle: 'Material from your own session (optional)',
    setupContextOff: 'Off',
    setupContextOn: 'On',
    setupContextNote: "On: short excerpts of your last prompt and of Claude's last reply (secrets and emails redacted) go to the tutor, on your Claude plan, as topic ideas. Off by default.",
    setupSummaryContext: (isOn) => `Material from your session: ${isOn ? 'on' : 'off'}`,
    setupSummary: 'Summary',
    setupSummaryLanguages: (target, native, level) => `${target} from ${native}, level ${level}`,
    setupSummaryInterests: (interests) => `Interests: ${interests.length === 0 ? '(none)' : interests.join(', ')}`,
    setupSummaryLook: (share, tutor, theme) => `Split ${share} % · tutor ${tutor} · theme ${theme}`,
    setupSaved: 'lingo-pane: setup saved',
    setupPendingToast: 'lingo-pane: setup pending. Run /lingo setup (or press 2 in the band above the prompt).',
    setupNeedsInput: 'Setup needs a terminal or the desktop app.',
    learning: (target, native) => `Learning ${target} from ${native}.`,
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    confirm: 'Confirm',
    // --- The split -------------------------------------------------------------------
    keysHere: '● keys here · Esc back to the prompt',
    keysAway: '○ Ctrl+X Tab to come back',
    waitingForYou: 'Claude needs you: answer below. The lesson waits here.',
    // --- The lesson ----------------------------------------------------------------
    tutor: 'tutor  ',
    you: 'you    ',
    help: 'help   ',
    tutorThinking: 'the tutor is thinking…',
    tutorSilentOpening: 'The tutor did not answer. Press "switch ▸" to try again or pick another activity.',
    tutorSilentReply: 'The tutor did not answer; your line is back to you: send it again.',
    tutorSilentHelp: 'The tutor did not answer. Try Enter on the empty field again.',
    replyPlaceholder: (target) => `reply in ${target}`,
    replySubmit: 'reply',
    listen: '🔊 listen',
    switchActivity: 'switch ▸',
    talkHint: '⏎ empty = help · Tab = listen and switch',
    talkHintWaiting: 'the tutor is answering; send your next line once it has',
    nextActivity: (label) => `next: ${label} ▸`,
    levelHint: (direction, level) => direction === 'up'
        ? `Tutor: these went smoothly. You could try ${level}; /lingo setup changes it.`
        : `Tutor: these were hard. ${level} might suit you better for now; /lingo setup changes it.`,
    madeUpScenario: (title) => `${title} (made up from your interests)`,
    scene: (situation, learnerRole) => `${situation} You: ${learnerRole}`,
    readingWriting: 'the tutor is writing a short text for you…',
    readingSilent: 'The tutor did not write the text. Try again with "next" or pick another activity.',
    readingGenerated: 'Written by the tutor for your level; it can make mistakes.',
    readingQuestion: (n, of, question) => `Q${n} of ${of}: ${question}`,
    readingPlaceholder: 'a word or three',
    readingNotQuite: 'Not quite. Look again, or Enter on the empty field shows it.',
    readingAnswered: (n, question, answer, isRight) => `${isRight ? '✓' : '·'} Q${n} ${question} ${answer}`,
    readingHint: '⏎ empty = show the answer (it becomes a card) · Tab = listen and switch',
    current: '(current)',
    backToField: 'back',
    menuHint: (count) => `press 1-${count} · Tab back`,
    // --- Review (the built-in pack) ---------------------------------------------------
    reviewPackNote: (title) => `The built-in pack is ${title}; it is used for now.`,
    reviewDemoFinished: (count) => `Demo finished: all ${count} lessons are done. Come back to review, or wait for the lesson generator.`,
    reviewLessonIntro: (lesson, count, recall, fresh) => `Lesson ${lesson} of ${count}: ${recall} to recall, ${fresh} new.`,
    reviewMistakesIntro: (count) => `Your mistakes: ${count} to review.`,
    reviewMistakeOf: (card, of) => `Your mistake - card ${card} of ${of}: type the right words for the marked ones`,
    reviewDone: 'Review done',
    reviewStart: 'Start lesson',
    reviewLessonDone: (lesson) => `Lesson ${lesson} done`,
    reviewDemoLast: 'Demo finished: that was the last lesson.',
    reviewContinue: 'Continue',
    reviewCardOf: (lesson, card, of, isRecall) => `Lesson ${lesson} - card ${card} of ${of} (${isRecall ? 'recall' : 'new'})`,
    reviewIn: (target) => `In ${target}: `,
    reviewPlaceholder: 'type your answer',
    reviewSubmit: 'answer',
    reviewNotYet: (hint) => `Not yet. ${hint}`,
    reviewHintFromTutor: 'Hint from tutor',
    reviewHint: '⏎ empty = show the answer · Tab = hint from tutor, switch',
    reviewCorrect: (answer) => `Correct: ${answer}`,
    reviewAnswer: (answer) => `Answer: ${answer}`,
    hintUnavailable: 'The tutor is not available right now. Use the hint above or try again.',
    hintLeaked: 'The tutor reply would have given the answer away, so it was dropped. Try again or look at the hint.',
    // --- Band above the prompt -----------------------------------------------------
    bandSetupPending: 'lingo-pane: setup pending. ',
    bandStartSetup: 'Start setup',
    bandLater: 'Later',
    bandOpenLesson: 'open lesson',
    // --- Theme command -------------------------------------------------------------
    themeSet: (label) => `lingo-pane: theme set to ${label}.`,
    themeNeedsSetup: 'lingo-pane: finish the setup first (/lingo setup).',
};
